/* ── Services ─────────────────────────────────────────────── */
export const SERVICES = [
  {
    slug: 'ai-development',
    title: 'AI活用型受託開発',
    titleEn: 'AI-Powered Development',
    icon: 'ai',
    tagline: '500万円のシステムが100万円で。',
    desc: '生成AIと20年の設計ノウハウを組み合わせ、コスト1/5〜1/10・納期最大1/10を実現。業務管理・予約・自動化システムに対応。',
    features: ['業務管理システム', '予約・顧客対応システム', '業務効率化・自動化'],
    path: '/services/ai-development',
    lpPath: '/lp/ai-development',
  },
  {
    slug: 'mobile',
    title: 'モバイルアプリ開発',
    titleEn: 'Mobile App Development',
    icon: 'mobile',
    tagline: 'Android黎明期から積み上げた実績。',
    desc: 'Android黎明期からの深い実績を持ち、FlutterによるiOS/Androidクロスプラットフォーム開発を提供。ネイティブ品質のUXをスピーディに実現します。',
    features: ['Flutter (iOS / Android)', 'ネイティブアプリ', 'PWA対応'],
    path: '/services/mobile',
  },
  {
    slug: 'web',
    title: 'Webシステム開発',
    titleEn: 'Web System Development',
    icon: 'web',
    tagline: 'スケールする設計で長く使えるシステムを。',
    desc: 'React・Next.js・Javaなど幅広いスタックに対応。要件定義から設計・開発・保守まで一貫して担当。長期運用を見据えたアーキテクチャを提案します。',
    features: ['フロントエンド開発', 'APIサーバー構築', 'クラウドインフラ設計'],
    path: '/services/web',
  },
  {
    slug: 'education',
    title: 'プログラミング教育',
    titleEn: 'Programming Education',
    icon: 'education',
    tagline: 'マインクラフトで楽しく学ぶプログラミング。',
    desc: 'マインクラフトを題材にした独自カリキュラムで子ども向けプログラミング教育を提供。教材・教育システムの受託開発も承ります。',
    features: ['子ども向けスクール (8x9)', '教材・カリキュラム開発', 'Mod・プラグイン開発'],
    path: '/services/education',
    externalPath: 'https://8x9.jp/',
  },
]

/* ── Works / Case Studies ─────────────────────────────────── */
export const WORKS = [
  {
    slug: 'crm-manufacturing',
    industry: '製造業',
    service: 'ai-development',
    title: 'CRM・顧客管理システム構築',
    summary: '販売管理の属人化を解消し、営業生産性を大幅向上。',
    challenge: '社内の顧客・案件情報がExcelと担当者の頭の中にのみ存在し、属人化が深刻な課題でした。',
    solution: '生成AIを活用した設計フェーズの高速化により、要件定義から納品まで3週間で完了。',
    tech: ['React', 'Node.js', 'PostgreSQL'],
    before: { cost: '500万円', period: '5ヶ月' },
    after: { cost: '80万円', period: '3週間' },
    saving: 'コスト84%削減',
  },
  {
    slug: 'booking-service',
    industry: 'サービス業',
    service: 'ai-development',
    title: '予約・顧客対応システム開発',
    summary: 'LINE連携と自動返信で問い合わせ対応コストを大幅削減。',
    challenge: '電話・メールが混在する予約受付と問い合わせ対応にスタッフの半数が割かれていました。',
    solution: 'LINE公式アカウントと連携した予約管理システムを構築。自動返信・リマインドを実装。',
    tech: ['Vue.js', 'Python', 'MySQL', 'LINE API'],
    before: { cost: '300万円', period: '4ヶ月' },
    after: { cost: '60万円', period: '2週間' },
    saving: 'コスト80%削減',
  },
  {
    slug: 'inventory-wholesale',
    industry: '卸売業',
    service: 'ai-development',
    title: '在庫・受発注管理システム',
    summary: '手動Excelから脱却し、在庫ミスゼロ・発注コスト削減を達成。',
    challenge: '複数拠点のExcel管理による在庫差異が月次決算を常に遅延させていました。',
    solution: 'リアルタイム在庫同期と自動発注トリガーを実装したWebシステムを構築。',
    tech: ['React', 'Java', 'AWS'],
    before: { cost: '800万円', period: '6ヶ月' },
    after: { cost: '120万円', period: '4週間' },
    saving: 'コスト85%削減',
  },
  {
    slug: 'mobile-app-retail',
    industry: '小売業',
    service: 'mobile',
    title: 'スタッフ向け業務アプリ (Flutter)',
    summary: '紙の作業指示書をデジタル化し、報告工数を70%削減。',
    challenge: '現場スタッフへの作業指示と完了報告がすべて紙ベースで、集計に毎週丸1日かかっていました。',
    solution: 'Flutterで iOS/Android 両対応のスタッフ向けアプリを開発。オフライン対応も実装。',
    tech: ['Flutter', 'Firebase', 'Dart'],
    before: { cost: '250万円', period: '3ヶ月' },
    after: { cost: '70万円', period: '3週間' },
    saving: '工数70%削減',
  },
  {
    slug: 'booking-platform-web',
    industry: '教育業',
    service: 'web',
    title: 'オンライン予約・決済プラットフォーム',
    summary: 'Stripe連携で決済自動化。運営コスト月30万円削減。',
    challenge: '受講申込・入金確認・受領書発行がすべて手作業で、月に100件超の申込処理に追われていました。',
    solution: 'Stripe決済・自動領収書発行・受講管理を統合したWebプラットフォームを構築。',
    tech: ['Next.js', 'Stripe', 'Supabase'],
    before: { cost: '400万円', period: '5ヶ月' },
    after: { cost: '90万円', period: '4週間' },
    saving: '運営費月30万円削減',
  },
]

/* ── Blog Posts ───────────────────────────────────────────── */
export const BLOG_POSTS = [
  {
    slug: 'ai-development-cost-reduction',
    category: '開発事例',
    title: 'AI活用でシステム開発コストを1/5に削減した話',
    excerpt: '生成AIを設計・実装・テストに活用することで、従来比1/5のコストでシステム開発を実現した実践事例を紹介します。',
    date: '2025-05-20',
    readMin: 6,
  },
  {
    slug: 'flutter-cross-platform-2025',
    category: '技術',
    title: 'Flutter 3.x でのクロスプラットフォーム開発 — 2025年版',
    excerpt: 'iOS/Android/Web を一つのコードベースでカバーする Flutter の最新動向と実務での選択基準を解説します。',
    date: '2025-04-15',
    readMin: 8,
  },
  {
    slug: 'requirements-definition-ai',
    category: '開発手法',
    title: '要件定義にAIを使うと何が変わるか',
    excerpt: 'ChatGPT / Claude を要件定義フェーズに組み込んだことで、ドキュメント作成時間が従来の60%減になった経験を共有します。',
    date: '2025-03-08',
    readMin: 5,
  },
  {
    slug: 'minecraft-programming-education',
    category: '教育',
    title: 'マインクラフトで学ぶプログラミング — 子どもの学習効果を高める3つのポイント',
    excerpt: '8x9 Kidsスクールの運営を通じて見えてきた、ゲームを活用したプログラミング教育の効果的なアプローチを紹介します。',
    date: '2025-02-14',
    readMin: 7,
  },
  {
    slug: 'small-business-system-investment',
    category: 'ビジネス',
    title: '中小企業がシステム投資で失敗しないための5つの原則',
    excerpt: '多くの中小企業がシステム開発で失敗する共通のパターンと、それを避けるための実践的な考え方を解説します。',
    date: '2025-01-22',
    readMin: 6,
  },
  {
    slug: 'shibuya-office-move',
    category: 'お知らせ',
    title: '本社を東京・渋谷へ移転しました',
    excerpt: '2025年7月、株式会社ハックラボは東京都渋谷区渋谷2丁目に本社を移転いたしました。',
    date: '2025-07-01',
    readMin: 2,
  },
]

/* ── Careers ──────────────────────────────────────────────── */
export const JOB_OPENINGS = [
  {
    id: 'engineer-fullstack',
    title: 'Webエンジニア（フルスタック）',
    type: '正社員 / 業務委託',
    location: '東京・渋谷 / フルリモート可',
    tags: ['React', 'Node.js', 'TypeScript'],
    desc: 'AI活用型のWeb・業務システム開発をリードするエンジニアを募集。自社開発と受託開発の両方に携わります。',
  },
  {
    id: 'engineer-mobile',
    title: 'モバイルエンジニア（Flutter）',
    type: '正社員 / 業務委託',
    location: '東京・渋谷 / フルリモート可',
    tags: ['Flutter', 'Dart', 'Firebase'],
    desc: 'Flutter を使ったiOS/Android両対応のアプリ開発。アーキテクチャ設計から実装まで幅広く担当します。',
  },
  {
    id: 'pm',
    title: 'プロジェクトマネージャー',
    type: '正社員',
    location: '東京・渋谷',
    tags: ['PM', 'アジャイル', '要件定義'],
    desc: 'クライアントとの要件定義から納品までをリードするPMを募集。エンジニアとクライアントの橋渡し役。',
  },
]

/* ── Stats ────────────────────────────────────────────────── */
export const COMPANY_STATS = [
  { num: '15+', label: '年の開発実績' },
  { num: '300+', label: 'プロジェクト実績' },
  { num: '1/5〜1/10', label: 'コスト削減率' },
  { num: '2週間〜', label: '最短納品期間' },
]
